export const GET_TOTAL = "GET_TOTAL";
export const REDUCE_MALE_NUMBER = "REDUCE_MALE_NUMBER";
export const REDUCE_FEMALE_NUMBER = "REDUCE_FEMALE_NUMBER";
export const SAVE_MALE_TOTAL = "SAVE_MALE_TOTAL";
export const SAVE_FEMALE_TOTAL = "SAVE_FEMALE_TOTAL";
