export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
export const GET_TOTAL_AMOUNT = "GET_TOTAL_AMOUNT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const INCREASE_AMOUNT = "INCREASE_AMOUNT";
export const DECREASE_AMOUNT = "DECREASE_AMOUNT";
