export const DECREMENT_MALE_RHINOS = "DECREMENT_MALE_RHINOS";
export const DECREMENT_FEMALE_RHINOS = "DECREMENT_FEMALE_RHINOS";
export const GET_RHINO_TOTAL = "GET_RHINO_TOTAL";
export const SAVE_MALE_RHINO_TOTAL = "SAVE_MALE_RHINO_TOTAL";
export const SAVE_FEMALE_RHINO_TOTAL = "SAVE_FEMALE_RHINO_TOTAL";
